services:
  app:
    container_name: app-mov-to-mp4
    build: .
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      - PORT=${PORT:-4000}
      - API_URL=${API_URL:-http://localhost:4000}